name: 'direnv action'
description: 'Provides environment variables via direnv'
branding:
  icon: play
  color: green
inputs:
  masks:
    description: 'Comma separated list of environment variables to mask'
    required: true
    default: ''
  direnvVersion:
    description: 'direnv version to use'
    required: true
    default: '2.34.0'
runs:
  using: 'node20'
  main: 'dist/index.js'
